default:
  image: ${CI_REGISTRY}/android/shared/docker-android/oci:v2.0.0
  tags:
    - shared-small

variables:
  # Use fastzip to improve cache times
  #FF_USE_FASTZIP: "true"
  # Use no compression for artifacts
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  ATLAS_DEPLOY_ENV: "true"

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "candidate"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "candidate"

before_script:
  # We must keep these variables here. We can't do it inside the entrypoint, as idk how but
  # gitlab is going to convert them as a variable content instead of a variable file...
  - if [[ -f /load-env.sh ]]; then source /load-env.sh; fi
  - base64 -d - < "$PROTON_KEYSTORE_FILE" > app/protonkey.jks
  - base64 -d - < "$SERVICE_ACCOUNT_FILE" > app/service_account.json
  - md5sum app/protonkey.jks
  - md5sum app/service_account.json
  - git fetch --tags

stages:
  - i18n
  - prepare
  - analyze
  - deploy
  - build
  - startReview
  - test
  - report
  - publish
  - cleanup

prepare-build:
  stage: prepare
  artifacts:
    paths:
      - deploy.env
      - private.properties
    reports:
      dotenv: deploy.env
    expire_in: 1 week
  cache: []
  tags:
    - shared-small
  script:
    - echo PROXY_TOKEN="$(curl -o - https://proxy.proton.black/token/get)" >> deploy.env
    - echo "$PROTON_KEYSTORE_PRIVATE_PROPERTIES" >> private.properties

prepare-gradle-build-scan:
  stage: prepare
  tags:
    - shared-large
  script:
    - echo "BUILD_SCAN_PUBLISH=true" >> build_scan.env
  artifacts:
    reports:
      dotenv: build_scan.env
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^build/
    - if: $CI_COMMIT_REF_NAME =~ /^ci/
  cache: []

detekt analysis:
  stage: analyze
  tags:
    - shared-large
  script:
    - ./gradlew multiModuleDetekt --configuration-cache-problems=warn
  allow_failure: true
  artifacts:
    expire_in: 1 week
    reports:
      codequality: config/detekt/reports/mergedReport.json
  needs: []

.build:
  stage: build
  needs:
    - job: "prepare-build"
    - job: "prepare-gradle-build-scan"
      optional: true
  tags:
    - xlarge-k8s
  artifacts:
    expire_in: 1 week

build:dev:debug:
  extends: [.build]
  script:
    - ./gradlew assembleDevDebug --max-workers=4
    - ./gradlew assembleDevDebugAndroidTest --max-workers=4
    - |
      ./gradlew \
        :drive:crypto-base:domain:assembleDebugAndroidTest \
        :drive:files-list:assembleDebugAndroidTest \
        :drive:link:data:assembleDebugAndroidTest \
        :drive:sorting:presentation:assembleDebugAndroidTest
  artifacts:
    paths:
      - app/build/variables.env
      - ./**/*.apk
    reports:
      dotenv: app/build/variables.env

build alpha release:
  extends: [.build]
  script:
    - ./gradlew assembleAlphaRelease
  when: manual
  artifacts:
    paths:
      - app/build/outputs/apk/alpha/release
      - app/build/outputs/mapping/alphaRelease

build beta release:
  extends: [.build]
  script:
    - ./gradlew assembleBetaRelease
  when: manual
  artifacts:
    paths:
      - app/build/outputs/apk/beta/release
      - app/build/outputs/mapping/betaRelease

build prod release:
  extends: [.build]
  script:
    - ./gradlew assembleProdRelease
  when: manual
  artifacts:
    paths:
      - app/build/outputs/apk/prod/release
      - app/build/outputs/mapping/prodRelease

dev debug unit test:
  stage: test
  needs:
    - job: "build:dev:debug"
    - job: "prepare-gradle-build-scan"
      optional: true
  tags:
    - xlarge-k8s
  script:
    - ./gradlew testDevDebugUnitTest testDebugUnitTest
  artifacts:
    expire_in: 1 week
    reports:
      junit: ./**/build/test-results/test*DebugUnitTest/TEST-*.xml

upload to firebase:
  stage: startReview
  tags:
    - shared-medium
  script:
    - export $(cat app/build/variables.env)
    - gcloud config set project $CLOUD_PROJECT_ID --quiet
    - gcloud auth activate-service-account --key-file app/service_account.json --quiet
    - gsutil cp $LOCAL_APK $REMOTE_APK
    - gsutil cp $LOCAL_TEST_APK $REMOTE_TEST_APK
  cache: []

# Integration tests
.tests_preparation_script:
  image: $CI_REGISTRY/tpe/test-scripts
  stage: test
  tags:
    - shared-medium
  variables:
    RESULTS_DIR: "${FIREBASE_RESULT_ROOT}/${CI_JOB_NAME}"
    FIREBASE_LOG_FILE: "${CI_JOB_NAME}.firebase_log"
    DEVICE_CONFIG: "quickTest"
  script:
    - echo ${ENV_VARIABLES}
    - gcloud config set project $CLOUD_PROJECT_ID --quiet
    - gcloud auth activate-service-account --key-file app/service_account.json --quiet
    - gcloud firebase test android run firebase-device-config.yml:${DEVICE_CONFIG}
      --app $REMOTE_APK
      --test $TEST_APP
      --num-flaky-test-attempts=1
      --environment-variables "${ENV_VARIABLES}"
      --directories-to-pull /sdcard/Download,/sdcard/Pictures/Screenshots
      --results-dir="${RESULTS_DIR}"
      --test-targets="${TEST_TARGETS}"
      --test-runner-class="${TEST_RUNNER_CLASS}"
      --use-orchestrator 2>&1 | tee $FIREBASE_LOG_FILE
  after_script:
    # Prepare and pull artifacts
    - mkdir firebase_artifacts
    - gsutil ls $GCLOUD_BUCKET_URL/$RESULTS_DIR | grep '/$' | gsutil -m cp -r -I ./firebase_artifacts
    - echo "" >> $FIREBASE_LOG_FILE
    - echo GITLAB_JOB_URL=$CI_JOB_URL >> $FIREBASE_LOG_FILE
    - echo GITLAB_JOB_NAME=$CI_JOB_NAME >> $FIREBASE_LOG_FILE
    # Attach screenshots and improve readability for Gitlab test report
    - process_firebase_report.py
      --path firebase_artifacts
      --screenshots artifacts/sdcard/Pictures/Screenshots
      --remove-prefix me.proton.
    # Merge reports from multiple firebase devices into one
    - merge_reports.py
      --path firebase_artifacts
      --output ${CI_JOB_NAME}_report.xml
  artifacts:
    expire_in: 1 week
    paths:
      - ./**/${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}.ec
      - firebase_artifacts
      - ./${CI_JOB_NAME}.firebase_log
      - firebase_output.txt
      - ${CI_JOB_NAME}_report.xml
    reports:
      junit: ${CI_JOB_NAME}_report.xml
    when: always
  cache: []

.drive-module-tests:
  extends: .tests_preparation_script
  variables:
    TEST_PACKAGE: ${PACKAGE_NAME//-/.}
    TEST_APP: "drive/${PACKAGE_NAME}/build/outputs/apk/androidTest/debug/*.apk"
    TEST_TARGETS: "package me.proton.core.drive.$TEST_PACKAGE"
    TEST_RUNNER_CLASS: "androidx.test.runner.AndroidJUnitRunner"
    ENV_VARIABLES: 'coverage=true,coverageFile="/sdcard/Download/${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}.ec",clearPackageData=true'

drive-crypto-base-domain-firebase-tests:
  extends: .drive-module-tests
  variables:
    PACKAGE_NAME: "crypto-base/domain"
    TEST_PACKAGE: "cryptobase.domain"

drive-files-list-firebase-tests:
  extends: .drive-module-tests
  variables:
    PACKAGE_NAME: "files-list"
    TEST_PACKAGE: "files"

drive-link-data-firebase-tests:
  extends: .drive-module-tests
  variables:
    PACKAGE_NAME: "link/data"
    TEST_PACKAGE: "link.data"

drive-sorting-presentation-firebase-tests:
  extends: .drive-module-tests
  variables:
    PACKAGE_NAME: "sorting/presentation"

.app-firebase-tests:
  extends: .tests_preparation_script
  variables:
    TEST_APP: "$REMOTE_TEST_APK"
    TEST_RUNNER_CLASS: "me.proton.android.drive.ui.HiltTestRunner"
    ENV_VARIABLES: "host=${DYNAMIC_DOMAIN},proxyToken=${PROXY_TOKEN},clearPackageData=true,debug=false"
  allow_failure: true
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: manual

test:firebase:e2e:smoke:
  extends: .app-firebase-tests
  when: manual
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: on_success
  variables:
    TEST_TARGETS: "annotation me.proton.android.drive.ui.test.SmokeTest"

test:firebase:e2e:account:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.account"

test:firebase:e2e:creatingFolder:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.creatingFolder"

test:firebase:e2e:details:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.details"

test:firebase:e2e:move:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.move"
    DEVICE_CONFIG: "quickTest-2"

test:firebase:e2e:offline:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.offline"

test:firebase:e2e:rename:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.rename"

test:firebase:e2e:settings:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.settings"
    DEVICE_CONFIG: "quickTest-3"

test:firebase:e2e:share:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.share"
    DEVICE_CONFIG: "quickTest-2"

test:firebase:e2e:subscription:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.subscription"

test:firebase:e2e:trash:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.trash"

test:firebase:e2e:upload:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.upload"

test:firebase:e2e:photos:
  extends: .app-firebase-tests
  variables:
    TEST_TARGETS: "package me.proton.android.drive.ui.test.flow.photos"

coverage report:
  stage: report
  tags:
    - xlarge-k8s
  script:
    - ./gradlew coberturaCoverageReport
  allow_failure: true
  coverage: '/Total coverage: \d+.\d+/'
  artifacts:
    expire_in: 1 week
    paths:
      - ./**/build/reports/*
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./**/build/reports/cobertura-coverage.xml
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: manual

testmo-upload:
  stage: report
  allow_failure: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: manual
  before_script:
    - if [[ -f /load-env.sh ]]; then source /load-env.sh; fi
  variables:
    PROJECT_ID: "25"
    NAME: $CI_COMMIT_TITLE
    MILESTONE: $ARCHIVES_VERSION
    TAGS: $CI_PIPELINE_SOURCE
    SOURCE: $CI_COMMIT_REF_SLUG
    RESULT_FOLDER: "./*.xml"
  cache: []

report:slack:
  image: $CI_REGISTRY/tpe/test-scripts
  stage: report
  when: always
  allow_failure: true
  tags:
    - shared-small
  script:
    - firebase_reporter.py
      --path .
      --slack-channel drive-android-ci-reports
  cache: []

publish to firebase app distribution:
  stage: publish
  tags:
    - xlarge-k8s
  script:
    - export $(cat deploy.env)
    - ./gradlew :app:publishGeneratedReleaseNotes --configuration-cache-problems=warn
    - wget --quiet --output-document=/tmp/firebase https://firebase.tools/bin/linux/latest
    - mkdir -p /opt/firebase-cli/
    - cp /tmp/firebase /opt/firebase-cli/firebase
    - chmod +x /opt/firebase-cli/firebase
    - /opt/firebase-cli/firebase appdistribution:distribute $LOCAL_APK
      --app 1:141471569432:android:1ba11f1b1e26e08ab7956d
      --release-notes-file "app/src/main/play/release-notes/en-US/default.txt"
      --groups "qa-team, dev-team, management-team"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: manual
      allow_failure: true

startReview:
  needs:
    - job: "prepare-build"
    - job: "build:dev:debug"
  tags:
    - shared-medium
  before_script:
    - if [[ -f /load-env.sh ]]; then source /load-env.sh; fi
    - export REVIEW_APP_ARTIFACT_PATH=$LOCAL_APK
    - echo ${REVIEW_APP_ARTIFACT_PATH}
  extends: .startReview
  cache: []

stopReview:
  stage: cleanup
  needs:
    - job: "startReview"
  before_script: []
  extends: .stopReview
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: manual
      allow_failure: true

include:
  - project: 'proton/mobile/android/proton-libs'
    ref: main
    file: '/ci/templates-shared/appetize-integration.yml'
  - project: 'proton/devops/atlas-deploy'
    ref: main
    file: '/scenarios/pipeline-env.yml'
  - project: 'tpe/testmo-reporter'
    ref: master
    file: '/scenarios/testmo-simple.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'

i18n-sync-crowdin:
  stage: i18n
  variables:
    I18N_SYNC_BRANCH: develop
    I18N_SYNC_CROWDIN_PROJECT: 'android-drive'
  extends: .i18n-sync-crowdin-shared

i18n-commit-locales:
  stage: i18n
  variables:
    I18N_COMMIT_BRANCH_PUSH: develop
    I18N_COMMIT_BRANCH_ALLOWED: develop
    I18N_COMMIT_CROWDIN_PROJECT: 'android-drive'
  extends: .i18n-commit-locales-shared
