quickTest:
  timeout: 30m
  device:
    - model: MediumPhone.arm
      version: 33
    - model: Pixel2
      version: 30
quickTest-2:
  timeout: 30m
  device:
    - model: Pixel2.arm
      version: 33
    - model: Pixel3
      version: 30
quickTest-3:
  timeout: 30m
  device:
    - model: SmallPhone.arm
      version: 33
    - model: NexusLowRes
      version: 30

